[skip ci] .gitlab-ci.yml - change workplace rebase to merge and trigger variable to BUILD

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,7 +22,7 @@ merge_free:
     - git-octopus
   except:
     variables:
-      - $REBASE == "workplace"
+      - $BUILD == "workplace"
   script:
     - git remote set-url --push origin $PUSH_REPO
     - git checkout CLOUD-$MOODLE_VERSION/base
@@ -40,7 +40,7 @@ merge_school:
     - git-octopus
   except:
     variables:
-      - $REBASE == "workplace"
+      - $BUILD == "workplace"
   script:
     - git remote set-url --push origin $PUSH_REPO
     - git checkout CLOUD-$MOODLE_VERSION/base
@@ -58,7 +58,7 @@ merge_starter:
     - git-octopus
   except:
     variables:
-      - $REBASE == "workplace"
+      - $BUILD == "workplace"
   script:
     - git remote set-url --push origin $PUSH_REPO
     - git checkout CLOUD-$MOODLE_VERSION/base
@@ -76,7 +76,7 @@ merge_testing_school:
     - git-octopus
   except:
     variables:
-      - $REBASE == "workplace"
+      - $BUILD == "workplace"
   script:
     - git remote set-url --push origin $PUSH_REPO
     - git checkout CLOUD-$MOODLE_VERSION/base
@@ -97,14 +97,14 @@ merge_workplace:
     - git checkout CLOUD-$MOODLE_VERSION/FEATURE-Workplace
     - git reset --hard origin/CLOUD-$MOODLE_VERSION/FEATURE-Workplace
     - >
-      if [ "$REBASE" == "workplace" ]; then
-        echo "======= Rebasing to latest workplace version ======="
+      if [ "$BUILD" == "workplace" ]; then
+        echo "======= Merging latest workplace code ======="
         MAJOR_VERSION=${MOODLE_VERSION::-2}
         grep workplacebuild .git/config || git remote add workplacebuild git@git.in.moodle.com:workplace/workplacebuild.git
         git fetch workplacebuild WP-${MAJOR_VERSION}-build-workplace_moodlecloud || ( echo "======= FAILED TO FETCH WORKPLACE BUILD"; exit 1 )
-        git rebase workplacebuild/WP-${MAJOR_VERSION}-build-workplace_moodlecloud || ( echo "======= FAILED TO REBASE ======="; exit 1 )
+        git merge workplacebuild/WP-${MAJOR_VERSION}-build-workplace_moodlecloud || ( echo "======= FAILED TO MERGE WORKPLACE ======="; exit 1 )
         git push origin || ( echo "======= FAILED TO PUSH ======="; exit 1 )
-        echo "======= Rebase successfull ======="
+        echo "======= Merge successfull ======="
       fi
     - export WORKPLACE_BRANCHES=`eval "echo \\$$(echo WORKPLACE_BRANCHES_${SHORT_VERSION})" |sed -e "s#FEATURE-#origin/CLOUD-$MOODLE_VERSION/FEATURE-#g"`
     - git octopus $WORKPLACE_BRANCHES origin/CLOUD-$MOODLE_VERSION/FEATURE-Workplace
